### ISSUE TITLE
Opening log for compose failed

### ISSUE THREAD

**Issue by atodorov** [osbuild/osbuild-composer#586]
osbuild-composer-10-1.20200429git3fba68c.fc31.x86_64
composer-cli-31.9-1.fc31.x86_64

```
# composer-cli compose list
7b594614-079a-4839-8678-ea2830e590ef FAILED test-http-server 0.0.1 Tar
fe07280b-b047-47eb-8625-e2640304aea7 FAILED test-http-server 0.0.2 Tar
[root@kvm-02-guest21 lorax]# composer-cli compose info fe07280b-b047-47eb-8625-e2640304aea7
fe07280b-b047-47eb-8625-e2640304aea7 FAILED   test-http-server 0.0.2 tar              2147483648
Packages:
    openssh-server-*
Modules:
    httpd-2.4.*
    php-7.*
Dependencies:
[root@kvm-02-guest21 lorax]# composer-cli compose logs fe07280b-b047-47eb-8625-e2640304aea7
Opening log for compose fe07280b-b047-47eb-8625-e2640304aea7 failed
```

I am trying to debug failures from https://github.com/weldr/lorax/pull/1007 with the osbuild-composer backend (looks like depsolve failures) but I can't get any logs. 

With the new backend I'm not sure where to search for logs on the file system.

**Comment by atodorov** [comment]
Looks like #524, retrying a newer version.

**Comment by ondrejbudai** [comment]
This was fixed in version 11, see `NEWD.md`

**Comment by atodorov** [comment]
> This was fixed in version 11, see `NEWD.md`

Doesn't work for me. I've updated to latest master and rebuilt the RPMs from source then installed the new RPMs on the system; restarted osbuild-composer and osbuild-worker@1 services.

All RPMs are now version 11-1.20200504git3ba8c79.fc31.

When I execute the test script from the lorax repo it results in a failing compose but I'm still not able to get the logs.

**Comment by atodorov** [comment]
This issue is more complex and is different from the previous one about missing logs. Here is more info from @ondrejbudai:

1) `compose cancel` is not implemented, therefore it will always fail with 404. I think we should implement it, can you please ping Tom? We even have a PR for that, see https://github.com/osbuild/osbuild-composer/pull/180

So the composer-cli test script which I am actually trying to execute (over at lorax'es repository) fails. The glue code which we have around these scripts restarts the daemon in its teardown section.


2) Then a very interesting sequence of events happen - composer and worker are restarted.  (all test scripts have exited or are about to exit) Composer sees that it should have a job running, but we don't support "resuming" a job, so it marks it as failed. **BUT it doesn't create any logs for it because it has none.**

And that's definitely a bug - it should at least create a log containing something like "job failed because of unexpected composer shutdown"
